/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: dhcpd.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _DHCPD_H_
#define _DHCPD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef dhcpd__ns
#define dhcpd__ns 1816715834
#define dhcpd__ns_id "http://univ-tlse3.fr/ns/dhcpd"
#define dhcpd__ns_uri "http://univ-tlse3.fr/ns/dhcpd"
#endif

#define dhcpd_defaultLeaseTime 118129111
#define dhcpd_subNetworks 68952590
#define dhcpd_dns 577671700
#define dhcpd_range 28853268
#define dhcpd_dhcp 990408299
#define dhcpd_net 872020178
#define dhcpd_mask 1167181041
#define dhcpd_kern 0
#define dhcpd_local7 2
#define dhcpd_routers 1226429584
#define dhcpd_maxLeaseTime 636170887
#define dhcpd_hiAddr 1434563521
#define dhcpd_daemon 1
#define dhcpd_logFacility 255866064
#define dhcpd_subNetwork 127596482
#define dhcpd_lowAddr 1530146337
#define dhcpd_dynamicBootP 1183305956

#ifdef __cplusplus
}
#endif

#endif
